NUMPY

In [1]:
import numpy as np
intarr = np.array([1,2,3,4], int)
print(intarr) # syntax

[1 2 3 4]


In [ ]:
c = np.array([[1,2], [3,4]],complex)
print(c) # Complex array

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [ ]:
c = np.array([[[1,2], [3,4]], [[4,5], [6,7]]])
print(c) #3D array

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [ ]:
x = np.empty((2,2)) 
y = np.full((2,3), 5)
print(x)
print()
print(y)

[[0. 0.]
 [0. 0.]]

[[5 5 5]
 [5 5 5]]


In [24]:
a = np.random.random((4,3))
print(a)
a = np.arange(5)
print(a)
a = np.arange(5,20,5)
print(a)
a = np.linspace(0,2,5)
print(a)


[[0.11124293 0.40761827 0.13269218]
 [0.2794805  0.48393478 0.39155154]
 [0.98834653 0.54188792 0.29995923]
 [0.70955519 0.73788551 0.37542194]]
[0 1 2 3 4]
[ 5 10 15]
[0.  0.5 1.  1.5 2. ]


In [ ]:
x = np.eye(3) #Some variations from identity
y = np.identity(3)
print(x)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
a = np.array([[1,2,3,4], [2,3,4,6]])
t = 25 * np.sin(a)
print(t)

[[ 21.03677462  22.73243567   3.5280002  -18.92006238]
 [ 22.73243567   3.5280002  -18.92006238  -6.98538745]]


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a.sum())
print(a.min())
print()

21
1


In [2]:
a = np.array([[3,7,6], [1,5,2]])
b = np.array([[3,7,6], [1,5,2]])
a.sort()
b.sort(axis = 0)
print(a)
print(b)

[[3 6 7]
 [1 2 5]]
[[1 5 2]
 [3 7 6]]


In [7]:
"""a = np.array()
arange()
.zeros((3,4))
.ones()
linspace
"""
import numpy as np
arr = np.arange(1,31).reshape(6,5)
print(arr)
print(arr[0,0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
1
